### PR TITLE
Update easylist_cookie_specific_hide.txt

### PR DESCRIPTION
**Pull request by Sonic5435325**
Hide cookie notices on `puhekupla.com` and `senpa.io`.
Screenshot from 2023-06-29 20-27-24
Screenshot from 2023-06-29 20-28-58

### CODE REVIEW

**Comment by Mistik** [comment]
It literally only appears once, and once you press accept it won’t appear again.

It’s a legal requirement lol, why are you so against it?

**Comment by Sonic5435325** [comment]
It was for an anti-cookie notice filter list for EasyList, since it's considered an "annoyance". Accidentally made my own pull request here because I'm a bit newer to pull requests in general.
If you have a problem with the filter being in EasyList, discuss with them about it: https://github.com/easylist/easylist

**Comment by Mistik** [comment]
You just press I accept once and you never have to press it again, but ok.

I just saw that you keep opening constant issues regarding Senpa. You know you could just ask in our discord server?

**Comment by Sonic5435325** [comment]
Thanks for the input. I usually just help report problems to the repo that this "repo" came from.
In EasyLIst Cookie, there is usually no exception to cookie notices being hidden/blocked.

**Comment by Mistik** [comment]
Ah ok cos I saw you also opened another for uBlock saying that right click didn’t work on Senpa.

The issue with that is that the game as right click as an assignable macro so having it enabled bugs up the game

**Comment by Sonic5435325** [comment]
Oh, I see. I didn't know of that, I mainly just report ads/tracking/annoyances to their most fitting filter list maintainers.
What ways does senpa.io bug up with right click enabled, may I ask?

**Pull request closed without merging**
